"""Agno agent responsible for generating consolidated news briefings."""

import json
from datetime import datetime

import pytz
from pydantic import BaseModel, Field

from briefing_bot.agents.base_agent import BaseAgent
from briefing_bot.models import Briefing, BriefingSection, NewsArticle, UserPreferences


class BriefingContent(BaseModel):
    """Structured briefing content generated by the AI agent."""

    content: str = Field(min_length=1)


class BriefingAgent(BaseAgent):
    """Agno-powered agent that writes final briefing text."""

    def __init__(self, model_id: str, agent: object | None = None) -> None:
        """Create the briefing generation agent.

        Args:
            model_id: OpenAI model id used by Agno.
            agent: Optional prebuilt agent, useful for tests.
        """
        super().__init__(model_id, _INSTRUCTIONS, agent)

    @property
    def agent_name(self) -> str:
        """Return the human-readable agent name.

        Returns:
            Agent name used in logs and debugging.
        """
        return "briefing"

    async def generate_briefing(
        self,
        preferences: UserPreferences,
        articles_by_topic: dict[str, list[NewsArticle]],
    ) -> Briefing:
        """Generate a complete briefing for one user.

        Args:
            preferences: User delivery preferences.
            articles_by_topic: Articles grouped by configured topic.

        Returns:
            Generated briefing ready for delivery.
        """
        sections = _build_sections(articles_by_topic)
        prompt = _build_prompt(preferences, sections)
        content = await self._generate_content(prompt, preferences, sections)
        return Briefing(user_id=preferences.user_id, content=content, sections=sections)

    async def _generate_content(
        self,
        prompt: str,
        preferences: UserPreferences,
        sections: list[BriefingSection],
    ) -> str:
        """Generate briefing text with a local fallback.

        Args:
            prompt: Prompt sent to the Agno agent.
            preferences: User delivery preferences.
            sections: Briefing sections to render.

        Returns:
            Briefing text.
        """
        try:
            result = await self._run_structured(prompt, BriefingContent)
            return result.content
        except Exception:
            return _render_local_briefing(preferences, sections)


def _build_sections(
    articles_by_topic: dict[str, list[NewsArticle]],
) -> list[BriefingSection]:
    """Convert grouped articles into briefing sections.

    Args:
        articles_by_topic: Articles grouped by configured topic.

    Returns:
        Briefing sections.
    """
    return [
        BriefingSection(topic=topic, articles=articles)
        for topic, articles in articles_by_topic.items()
    ]


def _build_prompt(
    preferences: UserPreferences,
    sections: list[BriefingSection],
) -> str:
    """Build the prompt used to generate final briefing content.

    Args:
        preferences: User delivery preferences.
        sections: Briefing sections to render.

    Returns:
        Prompt sent to the Agno agent.
    """
    payload = [section.model_dump(mode="json") for section in sections]
    date_text = _localized_date(preferences)
    articles_json = json.dumps(payload, ensure_ascii=False, indent=2)
    return _PROMPT_TEMPLATE.format(date=date_text, articles_json=articles_json)


def _render_local_briefing(
    preferences: UserPreferences,
    sections: list[BriefingSection],
) -> str:
    """Render a deterministic briefing when AI generation fails.

    Args:
        preferences: User delivery preferences.
        sections: Briefing sections to render.

    Returns:
        Briefing text following the required template.
    """
    lines = _briefing_header(preferences)
    for section in sections:
        lines.extend(_section_lines(section))
    lines.extend(_briefing_footer(sections))
    return "\n".join(lines)


def _briefing_header(preferences: UserPreferences) -> list[str]:
    """Build the briefing header lines.

    Args:
        preferences: User delivery preferences.

    Returns:
        Header lines.
    """
    return [
        f"📰 BRIEFING DIÁRIO — {_localized_date(preferences)}",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "",
    ]


def _section_lines(section: BriefingSection) -> list[str]:
    """Build lines for one topic section.

    Args:
        section: Briefing section to render.

    Returns:
        Topic section lines.
    """
    lines = [
        f"📌 TÓPICO: {section.topic}",
        *[_article_line(a) for a in section.articles],
    ]
    return [*lines, ""]


def _article_line(article: NewsArticle) -> str:
    """Build one article bullet line.

    Args:
        article: Article to render.

    Returns:
        Formatted article line.
    """
    summary = article.summary or "Resumo indisponível."
    return f"   • {article.title} — {summary} [{article.source}]"


def _briefing_footer(sections: list[BriefingSection]) -> list[str]:
    """Build the executive summary and closing lines.

    Args:
        sections: Briefing sections to summarize.

    Returns:
        Footer lines.
    """
    topics = ", ".join(section.topic for section in sections)
    return [
        "💡 RESUMO EXECUTIVO",
        f"   Principais atualizações consolidadas para: {topics}.",
        "",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "Briefing gerado automaticamente. Responda !config para alterar preferências.",
    ]


def _localized_date(preferences: UserPreferences) -> str:
    """Format today's date in the user's timezone.

    Args:
        preferences: User delivery preferences.

    Returns:
        Localized date in DD/MM/YYYY format.
    """
    timezone = pytz.timezone(preferences.timezone)
    return datetime.now(timezone).strftime("%d/%m/%Y")


_INSTRUCTIONS = [
    "You generate concise Portuguese news briefings.",
    "Follow the requested template exactly.",
    "Summaries must be factual and must not invent article details.",
]

_PROMPT_TEMPLATE = """
Generate a Portuguese briefing using exactly this structure:

📰 BRIEFING DIÁRIO — {date}
━━━━━━━━━━━━━━━━━━━━━━━━━━

📌 TÓPICO: {{topic}}
   • {{title}} — {{summary in 1-2 lines}} [{{source}}]

💡 RESUMO EXECUTIVO
   {{3-5 lines consolidating the most important developments}}

━━━━━━━━━━━━━━━━━━━━━━━━━━
Briefing gerado automaticamente. Responda !config para alterar preferências.

Use these grouped articles as source material:
{articles_json}
"""
